package io.provenance.explorer.domain.models.explorer.pulse

enum class MetricTrendType {
    UP,
    DOWN,
    FLAT
}

enum class MetricTrendPeriod {
    DAY,
}

enum class PulseCacheType {
    HASH_MARKET_CAP_METRIC,
    HASH_SUPPLY_METRIC,
    HASH_STAKED_METRIC,
    HASH_CIRCULATING_METRIC,
    PULSE_MARKET_CAP_METRIC,
    PULSE_TRANSACTION_VOLUME_METRIC,
    PULSE_FEES_AUCTIONS_METRIC,
    PULSE_RECEIVABLES_METRIC,
    PULSE_TRADE_SETTLEMENT_METRIC,
    PULSE_TRADE_VALUE_SETTLED_METRIC,
    PULSE_PARTICIPANTS_METRIC,
    PULSE_MARGIN_LOANS_METRIC,
    PULSE_DEMOCRATIZED_PRIME_POOLS_METRIC
}
