version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
registries:
  docker_hub:
    type: "docker-registry"
    url: "https://index.docker.io/v1/"
    username: "${{ secrets.DOCKERHUB_USERNAME }}"
    password: "${{ secrets.DOCKERHUB_TOKEN }}"
