
### Send Pulse backfill POST request
POST http://localhost:8612//api/pulse/metric/backfill
Content-Type: application/x-www-form-urlencoded
timeout: 1800000

fromDate = 2025-01-01 &
toDate = 2025-02-12 &
types = PULSE_MARKET_CAP_METRIC &
types = PULSE_TRANSACTION_VOLUME_METRIC &
types = HASH_MARKET_CAP_METRIC &
types = HASH_SUPPLY_METRIC &
types = HASH_STAKED_METRIC &
types = HASH_CIRCULATING_METRIC &
types = PULSE_MARKET_CAP_METRIC &
types = PULSE_TRANSACTION_VOLUME_METRIC &
types = PULSE_FEES_AUCTIONS_METRIC &
types = PULSE_TODAYS_NAV_METRIC &
types = PULSE_TOTAL_NAV_METRIC &
types = PULSE_TRADE_SETTLEMENT_METRIC &
types = PULSE_TRADE_VALUE_SETTLED_METRIC &
types = PULSE_PARTICIPANTS_METRIC &
types = PULSE_MARGIN_LOANS_METRIC &
types = PULSE_DEMOCRATIZED_PRIME_POOLS_METRIC &
types = PULSE_COMMITTED_ASSETS_VALUE_METRIC &
types = PULSE_COMMITTED_ASSETS_METRIC &
types = FTS_LOAN_TOTAL_BALANCE_METRIC &
types = FTS_LOAN_TOTAL_COUNT_METRIC &
types = FTS_LOAN_DISBURSEMENTS_METRIC &
types = FTS_LOAN_DISBURSEMENT_COUNT_METRIC &
types = FTS_LOAN_PAYMENTS_METRIC &
types = FTS_LOAN_TOTAL_PAYMENTS_METRIC


