version: '3.9'
services:
  explorer-postgres:
    image: provenanceio/explorer-database:latest
    container_name: explorer-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432

  explorer-service:
    image: provenanceio/explorer-service:latest
    container_name: explorer-service
    ports:
      - 8612:8612
    environment:
      - SPRING_PROFILES_ACTIVE=container
      - DB_USER=postgres
      - DB_PASS=password1
      - DB_HOST=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://explorer-postgres:5432/explorer
      - DB_PORT=5432
      - DB_NAME=explorer
      - DB_SCHEMA=explorer
      - DB_CONNECTION_POOL_SIZE=40
      - SPOTLIGHT_TTL_MS=5000
      - INITIAL_HIST_DAY_COUNT=14
      - EXPLORER_MAINNET=false
      # Hits the locally running node
      - EXPLORER_PB_URL=http://host.docker.internal:9090
      - EXPLORER_GENESIS_VERSION_URL=https://github.com/provenance-io/provenance/releases/download/v0.2.0/plan-v0.2.0.json
      - EXPLORER_UPGRADE_VERSION_REGEX=(v[0-9]+.[0-9]+.[0-9]+[-\\w\\d]*)
      - EXPLORER_UPGRADE_GITHUB_REPO=provenance-io/provenance
      - EXPLORER_HIDDEN_APIS=false
      - EXPLORER_SWAGGER_URL=localhost:8612
      - EXPLORER_SWAGGER_PROTOCOL=http
      - EXPLORER_PRICING_URL=https://test.figure.tech/service-pricing-engine/external
      # Replace with your CMC API key when using production
      - EXPLORER_CMC_API_KEY=b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c
      # Replace with {https://pro-api.coinmarketcap.com} when using in production
      - EXPLORER_CMC_API_URL=https://sandbox-api.coinmarketcap.com
      - EXPLORER_CMC_TOKEN_ID=19960
      - EXPLORER_FEE_BUG_RANGE_ONE_ELEVEN=8721085,10046412
    depends_on:
      - explorer-postgres
    links:
      - "explorer-postgres"

  explorer-frontend:
    image: provenanceio/explorer-frontend-generic:latest
    container_name: explorer-frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_ENV=local
    depends_on:
      - explorer-service
    links:
      - "explorer-service"
