// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

/**
 * <pre>
 * LatestNavEventRequest represents a request for the latest NAV events by price denom.
 * It requires a price denomination and at least one of `include_markers` or `include_scope` to be true.
 * </pre>
 *
 * Protobuf type {@code nav.LatestNavEventRequest}
 */
public final class LatestNavEventRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nav.LatestNavEventRequest)
    LatestNavEventRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LatestNavEventRequest.newBuilder() to construct.
  private LatestNavEventRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LatestNavEventRequest() {
    priceDenom_ = "";
    fromDate_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LatestNavEventRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LatestNavEventRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            priceDenom_ = s;
            break;
          }
          case 16: {

            includeMarkers_ = input.readBool();
            break;
          }
          case 24: {

            includeScope_ = input.readBool();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fromDate_ = s;
            break;
          }
          case 42: {
            io.provlabs.flow.api.PaginationRequest.Builder subBuilder = null;
            if (pagination_ != null) {
              subBuilder = pagination_.toBuilder();
            }
            pagination_ = input.readMessage(io.provlabs.flow.api.PaginationRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pagination_);
              pagination_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_LatestNavEventRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_LatestNavEventRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.provlabs.flow.api.LatestNavEventRequest.class, io.provlabs.flow.api.LatestNavEventRequest.Builder.class);
  }

  public static final int PRICE_DENOM_FIELD_NUMBER = 1;
  private volatile java.lang.Object priceDenom_;
  /**
   * <pre>
   * The denomination of the price to filter by.
   * </pre>
   *
   * <code>string price_denom = 1;</code>
   * @return The priceDenom.
   */
  @java.lang.Override
  public java.lang.String getPriceDenom() {
    java.lang.Object ref = priceDenom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      priceDenom_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The denomination of the price to filter by.
   * </pre>
   *
   * <code>string price_denom = 1;</code>
   * @return The bytes for priceDenom.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPriceDenomBytes() {
    java.lang.Object ref = priceDenom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      priceDenom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCLUDE_MARKERS_FIELD_NUMBER = 2;
  private boolean includeMarkers_;
  /**
   * <pre>
   * Boolean to include markers in the result.
   * </pre>
   *
   * <code>bool include_markers = 2;</code>
   * @return The includeMarkers.
   */
  @java.lang.Override
  public boolean getIncludeMarkers() {
    return includeMarkers_;
  }

  public static final int INCLUDE_SCOPE_FIELD_NUMBER = 3;
  private boolean includeScope_;
  /**
   * <pre>
   * Boolean to include scope in the result.
   * </pre>
   *
   * <code>bool include_scope = 3;</code>
   * @return The includeScope.
   */
  @java.lang.Override
  public boolean getIncludeScope() {
    return includeScope_;
  }

  public static final int FROM_DATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object fromDate_;
  /**
   * <pre>
   * Optional. The start date (in string format) to filter events from.
   * </pre>
   *
   * <code>string from_date = 4;</code>
   * @return The fromDate.
   */
  @java.lang.Override
  public java.lang.String getFromDate() {
    java.lang.Object ref = fromDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromDate_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. The start date (in string format) to filter events from.
   * </pre>
   *
   * <code>string from_date = 4;</code>
   * @return The bytes for fromDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromDateBytes() {
    java.lang.Object ref = fromDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGINATION_FIELD_NUMBER = 5;
  private io.provlabs.flow.api.PaginationRequest pagination_;
  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 5;</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return pagination_ != null;
  }
  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 5;</code>
   * @return The pagination.
   */
  @java.lang.Override
  public io.provlabs.flow.api.PaginationRequest getPagination() {
    return pagination_ == null ? io.provlabs.flow.api.PaginationRequest.getDefaultInstance() : pagination_;
  }
  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 5;</code>
   */
  @java.lang.Override
  public io.provlabs.flow.api.PaginationRequestOrBuilder getPaginationOrBuilder() {
    return getPagination();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPriceDenomBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, priceDenom_);
    }
    if (includeMarkers_ != false) {
      output.writeBool(2, includeMarkers_);
    }
    if (includeScope_ != false) {
      output.writeBool(3, includeScope_);
    }
    if (!getFromDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromDate_);
    }
    if (pagination_ != null) {
      output.writeMessage(5, getPagination());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPriceDenomBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, priceDenom_);
    }
    if (includeMarkers_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, includeMarkers_);
    }
    if (includeScope_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, includeScope_);
    }
    if (!getFromDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromDate_);
    }
    if (pagination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPagination());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.provlabs.flow.api.LatestNavEventRequest)) {
      return super.equals(obj);
    }
    io.provlabs.flow.api.LatestNavEventRequest other = (io.provlabs.flow.api.LatestNavEventRequest) obj;

    if (!getPriceDenom()
        .equals(other.getPriceDenom())) return false;
    if (getIncludeMarkers()
        != other.getIncludeMarkers()) return false;
    if (getIncludeScope()
        != other.getIncludeScope()) return false;
    if (!getFromDate()
        .equals(other.getFromDate())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRICE_DENOM_FIELD_NUMBER;
    hash = (53 * hash) + getPriceDenom().hashCode();
    hash = (37 * hash) + INCLUDE_MARKERS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeMarkers());
    hash = (37 * hash) + INCLUDE_SCOPE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeScope());
    hash = (37 * hash) + FROM_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getFromDate().hashCode();
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.LatestNavEventRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.provlabs.flow.api.LatestNavEventRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * LatestNavEventRequest represents a request for the latest NAV events by price denom.
   * It requires a price denomination and at least one of `include_markers` or `include_scope` to be true.
   * </pre>
   *
   * Protobuf type {@code nav.LatestNavEventRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nav.LatestNavEventRequest)
      io.provlabs.flow.api.LatestNavEventRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_LatestNavEventRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_LatestNavEventRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.provlabs.flow.api.LatestNavEventRequest.class, io.provlabs.flow.api.LatestNavEventRequest.Builder.class);
    }

    // Construct using io.provlabs.flow.api.LatestNavEventRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      priceDenom_ = "";

      includeMarkers_ = false;

      includeScope_ = false;

      fromDate_ = "";

      if (paginationBuilder_ == null) {
        pagination_ = null;
      } else {
        pagination_ = null;
        paginationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_LatestNavEventRequest_descriptor;
    }

    @java.lang.Override
    public io.provlabs.flow.api.LatestNavEventRequest getDefaultInstanceForType() {
      return io.provlabs.flow.api.LatestNavEventRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.provlabs.flow.api.LatestNavEventRequest build() {
      io.provlabs.flow.api.LatestNavEventRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.provlabs.flow.api.LatestNavEventRequest buildPartial() {
      io.provlabs.flow.api.LatestNavEventRequest result = new io.provlabs.flow.api.LatestNavEventRequest(this);
      result.priceDenom_ = priceDenom_;
      result.includeMarkers_ = includeMarkers_;
      result.includeScope_ = includeScope_;
      result.fromDate_ = fromDate_;
      if (paginationBuilder_ == null) {
        result.pagination_ = pagination_;
      } else {
        result.pagination_ = paginationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.provlabs.flow.api.LatestNavEventRequest) {
        return mergeFrom((io.provlabs.flow.api.LatestNavEventRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.provlabs.flow.api.LatestNavEventRequest other) {
      if (other == io.provlabs.flow.api.LatestNavEventRequest.getDefaultInstance()) return this;
      if (!other.getPriceDenom().isEmpty()) {
        priceDenom_ = other.priceDenom_;
        onChanged();
      }
      if (other.getIncludeMarkers() != false) {
        setIncludeMarkers(other.getIncludeMarkers());
      }
      if (other.getIncludeScope() != false) {
        setIncludeScope(other.getIncludeScope());
      }
      if (!other.getFromDate().isEmpty()) {
        fromDate_ = other.fromDate_;
        onChanged();
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.provlabs.flow.api.LatestNavEventRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.provlabs.flow.api.LatestNavEventRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object priceDenom_ = "";
    /**
     * <pre>
     * The denomination of the price to filter by.
     * </pre>
     *
     * <code>string price_denom = 1;</code>
     * @return The priceDenom.
     */
    public java.lang.String getPriceDenom() {
      java.lang.Object ref = priceDenom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        priceDenom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The denomination of the price to filter by.
     * </pre>
     *
     * <code>string price_denom = 1;</code>
     * @return The bytes for priceDenom.
     */
    public com.google.protobuf.ByteString
        getPriceDenomBytes() {
      java.lang.Object ref = priceDenom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        priceDenom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The denomination of the price to filter by.
     * </pre>
     *
     * <code>string price_denom = 1;</code>
     * @param value The priceDenom to set.
     * @return This builder for chaining.
     */
    public Builder setPriceDenom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      priceDenom_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The denomination of the price to filter by.
     * </pre>
     *
     * <code>string price_denom = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriceDenom() {
      
      priceDenom_ = getDefaultInstance().getPriceDenom();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The denomination of the price to filter by.
     * </pre>
     *
     * <code>string price_denom = 1;</code>
     * @param value The bytes for priceDenom to set.
     * @return This builder for chaining.
     */
    public Builder setPriceDenomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      priceDenom_ = value;
      onChanged();
      return this;
    }

    private boolean includeMarkers_ ;
    /**
     * <pre>
     * Boolean to include markers in the result.
     * </pre>
     *
     * <code>bool include_markers = 2;</code>
     * @return The includeMarkers.
     */
    @java.lang.Override
    public boolean getIncludeMarkers() {
      return includeMarkers_;
    }
    /**
     * <pre>
     * Boolean to include markers in the result.
     * </pre>
     *
     * <code>bool include_markers = 2;</code>
     * @param value The includeMarkers to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeMarkers(boolean value) {
      
      includeMarkers_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Boolean to include markers in the result.
     * </pre>
     *
     * <code>bool include_markers = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeMarkers() {
      
      includeMarkers_ = false;
      onChanged();
      return this;
    }

    private boolean includeScope_ ;
    /**
     * <pre>
     * Boolean to include scope in the result.
     * </pre>
     *
     * <code>bool include_scope = 3;</code>
     * @return The includeScope.
     */
    @java.lang.Override
    public boolean getIncludeScope() {
      return includeScope_;
    }
    /**
     * <pre>
     * Boolean to include scope in the result.
     * </pre>
     *
     * <code>bool include_scope = 3;</code>
     * @param value The includeScope to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeScope(boolean value) {
      
      includeScope_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Boolean to include scope in the result.
     * </pre>
     *
     * <code>bool include_scope = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeScope() {
      
      includeScope_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object fromDate_ = "";
    /**
     * <pre>
     * Optional. The start date (in string format) to filter events from.
     * </pre>
     *
     * <code>string from_date = 4;</code>
     * @return The fromDate.
     */
    public java.lang.String getFromDate() {
      java.lang.Object ref = fromDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. The start date (in string format) to filter events from.
     * </pre>
     *
     * <code>string from_date = 4;</code>
     * @return The bytes for fromDate.
     */
    public com.google.protobuf.ByteString
        getFromDateBytes() {
      java.lang.Object ref = fromDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. The start date (in string format) to filter events from.
     * </pre>
     *
     * <code>string from_date = 4;</code>
     * @param value The fromDate to set.
     * @return This builder for chaining.
     */
    public Builder setFromDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The start date (in string format) to filter events from.
     * </pre>
     *
     * <code>string from_date = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromDate() {
      
      fromDate_ = getDefaultInstance().getFromDate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. The start date (in string format) to filter events from.
     * </pre>
     *
     * <code>string from_date = 4;</code>
     * @param value The bytes for fromDate to set.
     * @return This builder for chaining.
     */
    public Builder setFromDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromDate_ = value;
      onChanged();
      return this;
    }

    private io.provlabs.flow.api.PaginationRequest pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.provlabs.flow.api.PaginationRequest, io.provlabs.flow.api.PaginationRequest.Builder, io.provlabs.flow.api.PaginationRequestOrBuilder> paginationBuilder_;
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return paginationBuilder_ != null || pagination_ != null;
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     * @return The pagination.
     */
    public io.provlabs.flow.api.PaginationRequest getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? io.provlabs.flow.api.PaginationRequest.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public Builder setPagination(io.provlabs.flow.api.PaginationRequest value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
        onChanged();
      } else {
        paginationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public Builder setPagination(
        io.provlabs.flow.api.PaginationRequest.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
        onChanged();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public Builder mergePagination(io.provlabs.flow.api.PaginationRequest value) {
      if (paginationBuilder_ == null) {
        if (pagination_ != null) {
          pagination_ =
            io.provlabs.flow.api.PaginationRequest.newBuilder(pagination_).mergeFrom(value).buildPartial();
        } else {
          pagination_ = value;
        }
        onChanged();
      } else {
        paginationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public Builder clearPagination() {
      if (paginationBuilder_ == null) {
        pagination_ = null;
        onChanged();
      } else {
        pagination_ = null;
        paginationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public io.provlabs.flow.api.PaginationRequest.Builder getPaginationBuilder() {
      
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    public io.provlabs.flow.api.PaginationRequestOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            io.provlabs.flow.api.PaginationRequest.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <pre>
     * Pagination details for the request
     * </pre>
     *
     * <code>.nav.PaginationRequest pagination = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.provlabs.flow.api.PaginationRequest, io.provlabs.flow.api.PaginationRequest.Builder, io.provlabs.flow.api.PaginationRequestOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.provlabs.flow.api.PaginationRequest, io.provlabs.flow.api.PaginationRequest.Builder, io.provlabs.flow.api.PaginationRequestOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nav.LatestNavEventRequest)
  }

  // @@protoc_insertion_point(class_scope:nav.LatestNavEventRequest)
  private static final io.provlabs.flow.api.LatestNavEventRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.provlabs.flow.api.LatestNavEventRequest();
  }

  public static io.provlabs.flow.api.LatestNavEventRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LatestNavEventRequest>
      PARSER = new com.google.protobuf.AbstractParser<LatestNavEventRequest>() {
    @java.lang.Override
    public LatestNavEventRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LatestNavEventRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LatestNavEventRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LatestNavEventRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.provlabs.flow.api.LatestNavEventRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

