// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

public interface LatestNavEventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nav.LatestNavEventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The denomination of the price to filter by.
   * </pre>
   *
   * <code>string price_denom = 1;</code>
   * @return The priceDenom.
   */
  java.lang.String getPriceDenom();
  /**
   * <pre>
   * The denomination of the price to filter by.
   * </pre>
   *
   * <code>string price_denom = 1;</code>
   * @return The bytes for priceDenom.
   */
  com.google.protobuf.ByteString
      getPriceDenomBytes();

  /**
   * <pre>
   * Boolean to include markers in the result.
   * </pre>
   *
   * <code>bool include_markers = 2;</code>
   * @return The includeMarkers.
   */
  boolean getIncludeMarkers();

  /**
   * <pre>
   * Boolean to include scope in the result.
   * </pre>
   *
   * <code>bool include_scope = 3;</code>
   * @return The includeScope.
   */
  boolean getIncludeScope();

  /**
   * <pre>
   * Optional. The start date (in string format) to filter events from.
   * </pre>
   *
   * <code>string from_date = 4;</code>
   * @return The fromDate.
   */
  java.lang.String getFromDate();
  /**
   * <pre>
   * Optional. The start date (in string format) to filter events from.
   * </pre>
   *
   * <code>string from_date = 4;</code>
   * @return The bytes for fromDate.
   */
  com.google.protobuf.ByteString
      getFromDateBytes();

  /**
   * <pre>
   * Optional. The maximum number of results to return. If not provided, defaults to 100.
   * </pre>
   *
   * <code>int32 limit = 5;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 6;</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 6;</code>
   * @return The pagination.
   */
  io.provlabs.flow.api.PaginationRequest getPagination();
  /**
   * <pre>
   * Pagination details for the request
   * </pre>
   *
   * <code>.nav.PaginationRequest pagination = 6;</code>
   */
  io.provlabs.flow.api.PaginationRequestOrBuilder getPaginationOrBuilder();
}
