// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

public interface NavEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nav.NavEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  java.util.List<io.provlabs.flow.api.NavEvent> 
      getNavEventsList();
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  io.provlabs.flow.api.NavEvent getNavEvents(int index);
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  int getNavEventsCount();
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  java.util.List<? extends io.provlabs.flow.api.NavEventOrBuilder> 
      getNavEventsOrBuilderList();
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  io.provlabs.flow.api.NavEventOrBuilder getNavEventsOrBuilder(
      int index);
}
