// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

/**
 * <pre>
 * NavEventResponse represents the response containing a list of NavEvents.
 * </pre>
 *
 * Protobuf type {@code nav.NavEventResponse}
 */
public final class NavEventResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nav.NavEventResponse)
    NavEventResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NavEventResponse.newBuilder() to construct.
  private NavEventResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NavEventResponse() {
    navEvents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NavEventResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NavEventResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              navEvents_ = new java.util.ArrayList<io.provlabs.flow.api.NavEvent>();
              mutable_bitField0_ |= 0x00000001;
            }
            navEvents_.add(
                input.readMessage(io.provlabs.flow.api.NavEvent.parser(), extensionRegistry));
            break;
          }
          case 18: {
            io.provlabs.flow.api.PaginationResponse.Builder subBuilder = null;
            if (pagination_ != null) {
              subBuilder = pagination_.toBuilder();
            }
            pagination_ = input.readMessage(io.provlabs.flow.api.PaginationResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pagination_);
              pagination_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        navEvents_ = java.util.Collections.unmodifiableList(navEvents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_NavEventResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_NavEventResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.provlabs.flow.api.NavEventResponse.class, io.provlabs.flow.api.NavEventResponse.Builder.class);
  }

  public static final int NAV_EVENTS_FIELD_NUMBER = 1;
  private java.util.List<io.provlabs.flow.api.NavEvent> navEvents_;
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.provlabs.flow.api.NavEvent> getNavEventsList() {
    return navEvents_;
  }
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.provlabs.flow.api.NavEventOrBuilder> 
      getNavEventsOrBuilderList() {
    return navEvents_;
  }
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  @java.lang.Override
  public int getNavEventsCount() {
    return navEvents_.size();
  }
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  @java.lang.Override
  public io.provlabs.flow.api.NavEvent getNavEvents(int index) {
    return navEvents_.get(index);
  }
  /**
   * <code>repeated .nav.NavEvent nav_events = 1;</code>
   */
  @java.lang.Override
  public io.provlabs.flow.api.NavEventOrBuilder getNavEventsOrBuilder(
      int index) {
    return navEvents_.get(index);
  }

  public static final int PAGINATION_FIELD_NUMBER = 2;
  private io.provlabs.flow.api.PaginationResponse pagination_;
  /**
   * <code>.nav.PaginationResponse pagination = 2;</code>
   * @return Whether the pagination field is set.
   */
  @java.lang.Override
  public boolean hasPagination() {
    return pagination_ != null;
  }
  /**
   * <code>.nav.PaginationResponse pagination = 2;</code>
   * @return The pagination.
   */
  @java.lang.Override
  public io.provlabs.flow.api.PaginationResponse getPagination() {
    return pagination_ == null ? io.provlabs.flow.api.PaginationResponse.getDefaultInstance() : pagination_;
  }
  /**
   * <code>.nav.PaginationResponse pagination = 2;</code>
   */
  @java.lang.Override
  public io.provlabs.flow.api.PaginationResponseOrBuilder getPaginationOrBuilder() {
    return getPagination();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < navEvents_.size(); i++) {
      output.writeMessage(1, navEvents_.get(i));
    }
    if (pagination_ != null) {
      output.writeMessage(2, getPagination());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < navEvents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, navEvents_.get(i));
    }
    if (pagination_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPagination());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.provlabs.flow.api.NavEventResponse)) {
      return super.equals(obj);
    }
    io.provlabs.flow.api.NavEventResponse other = (io.provlabs.flow.api.NavEventResponse) obj;

    if (!getNavEventsList()
        .equals(other.getNavEventsList())) return false;
    if (hasPagination() != other.hasPagination()) return false;
    if (hasPagination()) {
      if (!getPagination()
          .equals(other.getPagination())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNavEventsCount() > 0) {
      hash = (37 * hash) + NAV_EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getNavEventsList().hashCode();
    }
    if (hasPagination()) {
      hash = (37 * hash) + PAGINATION_FIELD_NUMBER;
      hash = (53 * hash) + getPagination().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.NavEventResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.NavEventResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.NavEventResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.provlabs.flow.api.NavEventResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * NavEventResponse represents the response containing a list of NavEvents.
   * </pre>
   *
   * Protobuf type {@code nav.NavEventResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nav.NavEventResponse)
      io.provlabs.flow.api.NavEventResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_NavEventResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_NavEventResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.provlabs.flow.api.NavEventResponse.class, io.provlabs.flow.api.NavEventResponse.Builder.class);
    }

    // Construct using io.provlabs.flow.api.NavEventResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNavEventsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (navEventsBuilder_ == null) {
        navEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        navEventsBuilder_.clear();
      }
      if (paginationBuilder_ == null) {
        pagination_ = null;
      } else {
        pagination_ = null;
        paginationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_NavEventResponse_descriptor;
    }

    @java.lang.Override
    public io.provlabs.flow.api.NavEventResponse getDefaultInstanceForType() {
      return io.provlabs.flow.api.NavEventResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.provlabs.flow.api.NavEventResponse build() {
      io.provlabs.flow.api.NavEventResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.provlabs.flow.api.NavEventResponse buildPartial() {
      io.provlabs.flow.api.NavEventResponse result = new io.provlabs.flow.api.NavEventResponse(this);
      int from_bitField0_ = bitField0_;
      if (navEventsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          navEvents_ = java.util.Collections.unmodifiableList(navEvents_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.navEvents_ = navEvents_;
      } else {
        result.navEvents_ = navEventsBuilder_.build();
      }
      if (paginationBuilder_ == null) {
        result.pagination_ = pagination_;
      } else {
        result.pagination_ = paginationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.provlabs.flow.api.NavEventResponse) {
        return mergeFrom((io.provlabs.flow.api.NavEventResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.provlabs.flow.api.NavEventResponse other) {
      if (other == io.provlabs.flow.api.NavEventResponse.getDefaultInstance()) return this;
      if (navEventsBuilder_ == null) {
        if (!other.navEvents_.isEmpty()) {
          if (navEvents_.isEmpty()) {
            navEvents_ = other.navEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNavEventsIsMutable();
            navEvents_.addAll(other.navEvents_);
          }
          onChanged();
        }
      } else {
        if (!other.navEvents_.isEmpty()) {
          if (navEventsBuilder_.isEmpty()) {
            navEventsBuilder_.dispose();
            navEventsBuilder_ = null;
            navEvents_ = other.navEvents_;
            bitField0_ = (bitField0_ & ~0x00000001);
            navEventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNavEventsFieldBuilder() : null;
          } else {
            navEventsBuilder_.addAllMessages(other.navEvents_);
          }
        }
      }
      if (other.hasPagination()) {
        mergePagination(other.getPagination());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.provlabs.flow.api.NavEventResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.provlabs.flow.api.NavEventResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<io.provlabs.flow.api.NavEvent> navEvents_ =
      java.util.Collections.emptyList();
    private void ensureNavEventsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        navEvents_ = new java.util.ArrayList<io.provlabs.flow.api.NavEvent>(navEvents_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.provlabs.flow.api.NavEvent, io.provlabs.flow.api.NavEvent.Builder, io.provlabs.flow.api.NavEventOrBuilder> navEventsBuilder_;

    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public java.util.List<io.provlabs.flow.api.NavEvent> getNavEventsList() {
      if (navEventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(navEvents_);
      } else {
        return navEventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public int getNavEventsCount() {
      if (navEventsBuilder_ == null) {
        return navEvents_.size();
      } else {
        return navEventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public io.provlabs.flow.api.NavEvent getNavEvents(int index) {
      if (navEventsBuilder_ == null) {
        return navEvents_.get(index);
      } else {
        return navEventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder setNavEvents(
        int index, io.provlabs.flow.api.NavEvent value) {
      if (navEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNavEventsIsMutable();
        navEvents_.set(index, value);
        onChanged();
      } else {
        navEventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder setNavEvents(
        int index, io.provlabs.flow.api.NavEvent.Builder builderForValue) {
      if (navEventsBuilder_ == null) {
        ensureNavEventsIsMutable();
        navEvents_.set(index, builderForValue.build());
        onChanged();
      } else {
        navEventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder addNavEvents(io.provlabs.flow.api.NavEvent value) {
      if (navEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNavEventsIsMutable();
        navEvents_.add(value);
        onChanged();
      } else {
        navEventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder addNavEvents(
        int index, io.provlabs.flow.api.NavEvent value) {
      if (navEventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNavEventsIsMutable();
        navEvents_.add(index, value);
        onChanged();
      } else {
        navEventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder addNavEvents(
        io.provlabs.flow.api.NavEvent.Builder builderForValue) {
      if (navEventsBuilder_ == null) {
        ensureNavEventsIsMutable();
        navEvents_.add(builderForValue.build());
        onChanged();
      } else {
        navEventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder addNavEvents(
        int index, io.provlabs.flow.api.NavEvent.Builder builderForValue) {
      if (navEventsBuilder_ == null) {
        ensureNavEventsIsMutable();
        navEvents_.add(index, builderForValue.build());
        onChanged();
      } else {
        navEventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder addAllNavEvents(
        java.lang.Iterable<? extends io.provlabs.flow.api.NavEvent> values) {
      if (navEventsBuilder_ == null) {
        ensureNavEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, navEvents_);
        onChanged();
      } else {
        navEventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder clearNavEvents() {
      if (navEventsBuilder_ == null) {
        navEvents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        navEventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public Builder removeNavEvents(int index) {
      if (navEventsBuilder_ == null) {
        ensureNavEventsIsMutable();
        navEvents_.remove(index);
        onChanged();
      } else {
        navEventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public io.provlabs.flow.api.NavEvent.Builder getNavEventsBuilder(
        int index) {
      return getNavEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public io.provlabs.flow.api.NavEventOrBuilder getNavEventsOrBuilder(
        int index) {
      if (navEventsBuilder_ == null) {
        return navEvents_.get(index);  } else {
        return navEventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public java.util.List<? extends io.provlabs.flow.api.NavEventOrBuilder> 
         getNavEventsOrBuilderList() {
      if (navEventsBuilder_ != null) {
        return navEventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(navEvents_);
      }
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public io.provlabs.flow.api.NavEvent.Builder addNavEventsBuilder() {
      return getNavEventsFieldBuilder().addBuilder(
          io.provlabs.flow.api.NavEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public io.provlabs.flow.api.NavEvent.Builder addNavEventsBuilder(
        int index) {
      return getNavEventsFieldBuilder().addBuilder(
          index, io.provlabs.flow.api.NavEvent.getDefaultInstance());
    }
    /**
     * <code>repeated .nav.NavEvent nav_events = 1;</code>
     */
    public java.util.List<io.provlabs.flow.api.NavEvent.Builder> 
         getNavEventsBuilderList() {
      return getNavEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.provlabs.flow.api.NavEvent, io.provlabs.flow.api.NavEvent.Builder, io.provlabs.flow.api.NavEventOrBuilder> 
        getNavEventsFieldBuilder() {
      if (navEventsBuilder_ == null) {
        navEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.provlabs.flow.api.NavEvent, io.provlabs.flow.api.NavEvent.Builder, io.provlabs.flow.api.NavEventOrBuilder>(
                navEvents_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        navEvents_ = null;
      }
      return navEventsBuilder_;
    }

    private io.provlabs.flow.api.PaginationResponse pagination_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.provlabs.flow.api.PaginationResponse, io.provlabs.flow.api.PaginationResponse.Builder, io.provlabs.flow.api.PaginationResponseOrBuilder> paginationBuilder_;
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     * @return Whether the pagination field is set.
     */
    public boolean hasPagination() {
      return paginationBuilder_ != null || pagination_ != null;
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     * @return The pagination.
     */
    public io.provlabs.flow.api.PaginationResponse getPagination() {
      if (paginationBuilder_ == null) {
        return pagination_ == null ? io.provlabs.flow.api.PaginationResponse.getDefaultInstance() : pagination_;
      } else {
        return paginationBuilder_.getMessage();
      }
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public Builder setPagination(io.provlabs.flow.api.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pagination_ = value;
        onChanged();
      } else {
        paginationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public Builder setPagination(
        io.provlabs.flow.api.PaginationResponse.Builder builderForValue) {
      if (paginationBuilder_ == null) {
        pagination_ = builderForValue.build();
        onChanged();
      } else {
        paginationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public Builder mergePagination(io.provlabs.flow.api.PaginationResponse value) {
      if (paginationBuilder_ == null) {
        if (pagination_ != null) {
          pagination_ =
            io.provlabs.flow.api.PaginationResponse.newBuilder(pagination_).mergeFrom(value).buildPartial();
        } else {
          pagination_ = value;
        }
        onChanged();
      } else {
        paginationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public Builder clearPagination() {
      if (paginationBuilder_ == null) {
        pagination_ = null;
        onChanged();
      } else {
        pagination_ = null;
        paginationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public io.provlabs.flow.api.PaginationResponse.Builder getPaginationBuilder() {
      
      onChanged();
      return getPaginationFieldBuilder().getBuilder();
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    public io.provlabs.flow.api.PaginationResponseOrBuilder getPaginationOrBuilder() {
      if (paginationBuilder_ != null) {
        return paginationBuilder_.getMessageOrBuilder();
      } else {
        return pagination_ == null ?
            io.provlabs.flow.api.PaginationResponse.getDefaultInstance() : pagination_;
      }
    }
    /**
     * <code>.nav.PaginationResponse pagination = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.provlabs.flow.api.PaginationResponse, io.provlabs.flow.api.PaginationResponse.Builder, io.provlabs.flow.api.PaginationResponseOrBuilder> 
        getPaginationFieldBuilder() {
      if (paginationBuilder_ == null) {
        paginationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.provlabs.flow.api.PaginationResponse, io.provlabs.flow.api.PaginationResponse.Builder, io.provlabs.flow.api.PaginationResponseOrBuilder>(
                getPagination(),
                getParentForChildren(),
                isClean());
        pagination_ = null;
      }
      return paginationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nav.NavEventResponse)
  }

  // @@protoc_insertion_point(class_scope:nav.NavEventResponse)
  private static final io.provlabs.flow.api.NavEventResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.provlabs.flow.api.NavEventResponse();
  }

  public static io.provlabs.flow.api.NavEventResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NavEventResponse>
      PARSER = new com.google.protobuf.AbstractParser<NavEventResponse>() {
    @java.lang.Override
    public NavEventResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NavEventResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NavEventResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NavEventResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.provlabs.flow.api.NavEventResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

