// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

public final class NavEventOuterClass {
  private NavEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nav_NavEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nav_NavEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nav_NavEventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nav_NavEventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nav_NavEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nav_NavEventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017nav_event.proto\022\003nav\"\354\001\n\010NavEvent\022\024\n\014b" +
      "lock_height\030\001 \001(\005\022\022\n\nblock_time\030\002 \001(\004\022\020\n" +
      "\010chain_id\030\003 \001(\005\022\017\n\007tx_hash\030\004 \001(\t\022\023\n\013even" +
      "t_order\030\005 \001(\005\022\022\n\nevent_type\030\006 \001(\t\022\020\n\010sco" +
      "pe_id\030\007 \001(\t\022\r\n\005denom\030\010 \001(\t\022\024\n\014price_amou" +
      "nt\030\t \001(\003\022\023\n\013price_denom\030\n \001(\t\022\016\n\006volume\030" +
      "\013 \001(\003\022\016\n\006source\030\014 \001(\t\"A\n\017NavEventRequest" +
      "\022\r\n\005denom\030\001 \001(\t\022\020\n\010scope_id\030\002 \001(\t\022\r\n\005lim" +
      "it\030\003 \001(\005\"5\n\020NavEventResponse\022!\n\nnav_even" +
      "ts\030\001 \003(\0132\r.nav.NavEvent2I\n\nNavService\022;\n" +
      "\014GetNavEvents\022\024.nav.NavEventRequest\032\025.na" +
      "v.NavEventResponseB \n\024io.provlabs.flow.a" +
      "piP\001Z\006/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nav_NavEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nav_NavEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nav_NavEvent_descriptor,
        new java.lang.String[] { "BlockHeight", "BlockTime", "ChainId", "TxHash", "EventOrder", "EventType", "ScopeId", "Denom", "PriceAmount", "PriceDenom", "Volume", "Source", });
    internal_static_nav_NavEventRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nav_NavEventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nav_NavEventRequest_descriptor,
        new java.lang.String[] { "Denom", "ScopeId", "Limit", });
    internal_static_nav_NavEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_nav_NavEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nav_NavEventResponse_descriptor,
        new java.lang.String[] { "NavEvents", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
