// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

/**
 * <pre>
 * Pagination response to provide pagination details in responses
 * </pre>
 *
 * Protobuf type {@code nav.PaginationResponse}
 */
public final class PaginationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nav.PaginationResponse)
    PaginationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaginationResponse.newBuilder() to construct.
  private PaginationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaginationResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaginationResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PaginationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentPage_ = input.readInt32();
            break;
          }
          case 16: {

            totalPages_ = input.readInt32();
            break;
          }
          case 24: {

            totalItems_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_PaginationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_PaginationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.provlabs.flow.api.PaginationResponse.class, io.provlabs.flow.api.PaginationResponse.Builder.class);
  }

  public static final int CURRENT_PAGE_FIELD_NUMBER = 1;
  private int currentPage_;
  /**
   * <pre>
   * The current page being returned
   * </pre>
   *
   * <code>int32 current_page = 1;</code>
   * @return The currentPage.
   */
  @java.lang.Override
  public int getCurrentPage() {
    return currentPage_;
  }

  public static final int TOTAL_PAGES_FIELD_NUMBER = 2;
  private int totalPages_;
  /**
   * <pre>
   * The total number of pages available
   * </pre>
   *
   * <code>int32 total_pages = 2;</code>
   * @return The totalPages.
   */
  @java.lang.Override
  public int getTotalPages() {
    return totalPages_;
  }

  public static final int TOTAL_ITEMS_FIELD_NUMBER = 3;
  private int totalItems_;
  /**
   * <pre>
   * The total number of items available across all pages
   * </pre>
   *
   * <code>int32 total_items = 3;</code>
   * @return The totalItems.
   */
  @java.lang.Override
  public int getTotalItems() {
    return totalItems_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentPage_ != 0) {
      output.writeInt32(1, currentPage_);
    }
    if (totalPages_ != 0) {
      output.writeInt32(2, totalPages_);
    }
    if (totalItems_ != 0) {
      output.writeInt32(3, totalItems_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentPage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentPage_);
    }
    if (totalPages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalPages_);
    }
    if (totalItems_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalItems_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.provlabs.flow.api.PaginationResponse)) {
      return super.equals(obj);
    }
    io.provlabs.flow.api.PaginationResponse other = (io.provlabs.flow.api.PaginationResponse) obj;

    if (getCurrentPage()
        != other.getCurrentPage()) return false;
    if (getTotalPages()
        != other.getTotalPages()) return false;
    if (getTotalItems()
        != other.getTotalItems()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPage();
    hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPages();
    hash = (37 * hash) + TOTAL_ITEMS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalItems();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.PaginationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.PaginationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.provlabs.flow.api.PaginationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.provlabs.flow.api.PaginationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Pagination response to provide pagination details in responses
   * </pre>
   *
   * Protobuf type {@code nav.PaginationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nav.PaginationResponse)
      io.provlabs.flow.api.PaginationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_PaginationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_PaginationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.provlabs.flow.api.PaginationResponse.class, io.provlabs.flow.api.PaginationResponse.Builder.class);
    }

    // Construct using io.provlabs.flow.api.PaginationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentPage_ = 0;

      totalPages_ = 0;

      totalItems_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.provlabs.flow.api.NavEventOuterClass.internal_static_nav_PaginationResponse_descriptor;
    }

    @java.lang.Override
    public io.provlabs.flow.api.PaginationResponse getDefaultInstanceForType() {
      return io.provlabs.flow.api.PaginationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.provlabs.flow.api.PaginationResponse build() {
      io.provlabs.flow.api.PaginationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.provlabs.flow.api.PaginationResponse buildPartial() {
      io.provlabs.flow.api.PaginationResponse result = new io.provlabs.flow.api.PaginationResponse(this);
      result.currentPage_ = currentPage_;
      result.totalPages_ = totalPages_;
      result.totalItems_ = totalItems_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.provlabs.flow.api.PaginationResponse) {
        return mergeFrom((io.provlabs.flow.api.PaginationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.provlabs.flow.api.PaginationResponse other) {
      if (other == io.provlabs.flow.api.PaginationResponse.getDefaultInstance()) return this;
      if (other.getCurrentPage() != 0) {
        setCurrentPage(other.getCurrentPage());
      }
      if (other.getTotalPages() != 0) {
        setTotalPages(other.getTotalPages());
      }
      if (other.getTotalItems() != 0) {
        setTotalItems(other.getTotalItems());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.provlabs.flow.api.PaginationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.provlabs.flow.api.PaginationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currentPage_ ;
    /**
     * <pre>
     * The current page being returned
     * </pre>
     *
     * <code>int32 current_page = 1;</code>
     * @return The currentPage.
     */
    @java.lang.Override
    public int getCurrentPage() {
      return currentPage_;
    }
    /**
     * <pre>
     * The current page being returned
     * </pre>
     *
     * <code>int32 current_page = 1;</code>
     * @param value The currentPage to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPage(int value) {
      
      currentPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The current page being returned
     * </pre>
     *
     * <code>int32 current_page = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPage() {
      
      currentPage_ = 0;
      onChanged();
      return this;
    }

    private int totalPages_ ;
    /**
     * <pre>
     * The total number of pages available
     * </pre>
     *
     * <code>int32 total_pages = 2;</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }
    /**
     * <pre>
     * The total number of pages available
     * </pre>
     *
     * <code>int32 total_pages = 2;</code>
     * @param value The totalPages to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPages(int value) {
      
      totalPages_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total number of pages available
     * </pre>
     *
     * <code>int32 total_pages = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPages() {
      
      totalPages_ = 0;
      onChanged();
      return this;
    }

    private int totalItems_ ;
    /**
     * <pre>
     * The total number of items available across all pages
     * </pre>
     *
     * <code>int32 total_items = 3;</code>
     * @return The totalItems.
     */
    @java.lang.Override
    public int getTotalItems() {
      return totalItems_;
    }
    /**
     * <pre>
     * The total number of items available across all pages
     * </pre>
     *
     * <code>int32 total_items = 3;</code>
     * @param value The totalItems to set.
     * @return This builder for chaining.
     */
    public Builder setTotalItems(int value) {
      
      totalItems_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The total number of items available across all pages
     * </pre>
     *
     * <code>int32 total_items = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalItems() {
      
      totalItems_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nav.PaginationResponse)
  }

  // @@protoc_insertion_point(class_scope:nav.PaginationResponse)
  private static final io.provlabs.flow.api.PaginationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.provlabs.flow.api.PaginationResponse();
  }

  public static io.provlabs.flow.api.PaginationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaginationResponse>
      PARSER = new com.google.protobuf.AbstractParser<PaginationResponse>() {
    @java.lang.Override
    public PaginationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PaginationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PaginationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaginationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.provlabs.flow.api.PaginationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

