// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nav_event.proto

package io.provlabs.flow.api;

public interface PaginationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nav.PaginationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The page number
   * </pre>
   *
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * The size of each page
   * </pre>
   *
   * <code>int32 page_size = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();
}
