name: Docker

on:
  push:
    branches-ignore: # Should publish on main and regular branches, but not release/ or tagged branches
      - 'release/**'
      - 'hotfix/**'
      - "v[0-9]+.[0-9]+.[0-9]+" # branches matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # branches matching v*, i.e. v1.0-rc1, v20.15.10-rc5
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=provenanceio/explorer-service
        VERSION=noop
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          echo ::set-output name=branch::${VERSION}
          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
            VERSION=latest
          fi
        fi
        TAGS="${DOCKER_IMAGE}:${VERSION}-${{github.run_number}}"
        if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
        fi
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=tags::${TAGS}
        echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push service docker
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile-service
        context: .
        push: true
        tags: ${{ steps.prep.outputs.tags }}
    - name: Build and push database docker
      uses: docker/build-push-action@v2
      if: ${{ steps.prep.outputs.branch == github.event.repository.default_branch }}
      with:
        file: docker/Dockerfile-database
        context: .
        push: true
        tags: provenanceio/explorer-database:latest
